# Generated by Django 2.2.4 on 2019-08-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='ru', max_length=3)),
                ('login', models.CharField(default='None', max_length=100)),
                ('expected_cmd', models.CharField(default='language', max_length=100)),
                ('first_act', models.CharField(default='None', max_length=100)),
                ('second_act', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
